### ISSUE TITLE
When target .NET not installed Visual Studio hangs because of modal dialog

### ISSUE THREAD

**Issue by xperiandri** [TargetFrameworkMigrator/TargetFrameworkMigrator#12]
When target .NET (in particular 4.5.2) not installed Visual Studio hangs because of modal dialog window opens and asks to choose what to do with a project which cannot be loaded because of absent target .NET version.
Definitely occurs when you migrate more that one project at once.

**Comment by 304NotModified** [comment]
Closing as inactive
