### ISSUE TITLE
It cannot migrate Portable Class Libraries

### ISSUE THREAD

**Issue by SuperJMN** [TargetFrameworkMigrator/TargetFrameworkMigrator#17]
The extension will not migrate any project that are Portable. I think there should be a option to update them, maybe separately, because In Portable Class Libraries there are "profiles". It would be handy if there is a list of Profiles in order to migrate to it.

**Comment by MartinPo** [comment]
Changing the "core" Framework is
      different from changing the PCL .
      Changing Framework is VS supported and VS itself change the
      project file.
      Changing PCL Framework is only change one entry in csproj file and
      so far as i know could only be done be editing csproj file.
      This could be easily done by simple replace function.
      If you like you can add this feature (not yet done) to
      https://visualstudiogallery.msdn.microsoft.com/e2dcdf06-444d-4501-8dae-732e76bc94aa
      
      
      Am 14.09.2015 um 23:51 schrieb José Manuel Nieto:
    
    
      The extension will not migrate any project that are Portable. I
        think there should be a option to update them, maybe separately,
        because In Portable Class Libraries there are "profiles". It
        would be handy if there is a list of Profiles in order to
        migrate to it.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by SuperJMN** [comment]
Thanks! but that extension doesn't support VS 2015.

**Comment by 304NotModified** [comment]
There a no plans anymore for this. So closing
