### ISSUE TITLE
Main dialog blocks other module dialogs

### ISSUE THREAD

**Issue by ayseff** [TargetFrameworkMigrator/TargetFrameworkMigrator#24]
So I was trying to Migrate my solution when I got an error message from Visual Studio saying that some sort of error occurs.  I didn't even see the message box.  I just tried to close the main dialog (Target Framework Migrator) and it was frozen so I couldn't.  When I hit alt + tab, I was able to see that there was a message box hidden behind it but it was inaccessible.  So I killed VS using task manager.  Opened up the TFM window again, MOVED IT TO ANOTHER PART OF THE SCREEN so that id wouldn't be in the default location where message boxes typically go, ran it again, got the error message, but this time I was able to see the message and close it out (add address it accordingly).  But there has to be another way...

Thanks,

**Comment by 304NotModified** [comment]
Closing as inactive
