### ISSUE TITLE
Finished project - merger request

### ISSUE THREAD

**Issue by hjkl950217** [TargetFrameworkMigrator/TargetFrameworkMigrator#30]
I translated this project into Simplified Chinese (UI) and would like to be able to push it.
Hope to build a branch of zh-hans that I will use to push.
Now, the push is off

**Comment by vansickle** [comment]
I would like to add a translation, if you'll make a pull request.

**Comment by hjkl950217** [comment]
I can use XML documents to do the source of the translation source, I can do Chinese translation

**Comment by hjkl950217** [comment]
my email addr:584880422@qq.com

**Comment by 304NotModified** [comment]
If this is still a good idea, please open a PR
