### ISSUE TITLE
Support .Net Standard/Portable Class Libraries, .Net Core

### ISSUE THREAD

**Issue by vansickle** [TargetFrameworkMigrator/TargetFrameworkMigrator#35]

**Comment by arpit-nagar** [comment]
Any updates on this ??

**Comment by xperiandri** [comment]
PCL added in #41 
.NET Core requires some new approach of migration which might be quite complex.

**Comment by 304NotModified** [comment]
https://github.com/TargetFrameworkMigrator/TargetFrameworkMigrator/issues/48 is planned for 1.8.
