### ISSUE TITLE
Support for .net 4.7.1

### ISSUE THREAD

**Issue by BADF00D** [TargetFrameworkMigrator/TargetFrameworkMigrator#38]
I just stumbled upon this awesome tool, but I can't use it, because it lacks support for .Net 4.7.1. 
I would add it myself, but I don't see where you get _Id_ property from in your [framework definition](https://github.com/VHQLabs/TargetFrameworkMigrator/blob/master/TargetFrameworkMigrator/Frameworks.xml).

**Comment by Daxito** [comment]
+1

**Comment by zpadilla-CLGX** [comment]
@BADF00D , the _Id_ property you are looking for is:
`<Framework Id="262407" Name=".NETFramework,Version=v4.7.1"/>`

**Comment by xperiandri** [comment]
Added dynamic loading by #41

**Comment by jgrandydev** [comment]
Appears to still not support 4.7.1

**Comment by xperiandri** [comment]
Author just disappeared somewhere and do not merge pull requests.
You can build it from my sources. See my fork

**Comment by conficient** [comment]
I tried several of the forks to try to get 4.7.1 support, but whichever one I build I get the same error running the VSIX - below is the relevant log entry:
```
29/03/2018 10:28:39 - Searching for applicable products...
29/03/2018 10:28:39 - Found installed product - Microsoft Visual Studio Enterprise 2015
29/03/2018 10:28:39 - Found installed product - Microsoft Visual Studio Professional 2015
29/03/2018 10:28:39 - Found installed product - Microsoft Visual Studio Community 2015
29/03/2018 10:28:39 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
29/03/2018 10:28:39 - Found installed product - Global Location
29/03/2018 10:28:39 - Found installed product - ssms
29/03/2018 10:28:39 - Found installed product - Visual Studio Enterprise 2017
29/03/2018 10:28:39 - Found installed product - Visual Studio Enterprise 2017 Preview
29/03/2018 10:28:39 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```
Anyone got any suggestions?

**Comment by xperiandri** [comment]
Go to VSIX project, open manifest, add entry for your VS SKU.
Which SKU do you use?

**Comment by conficient** [comment]
I have VS 2017 version 15.6.4 installed - the original VSIX (from the Extensions Gallery) installs fine, it's only when I try to compile and use the forks it doesn't work.

**Comment by xperiandri** [comment]
SKU means Community, Professional, Enterprise

**Comment by conficient** [comment]
Sorry, Enterprise (as per the log)
```
Found installed product - Visual Studio Enterprise 2017
```

**Comment by conficient** [comment]
Sorry can't do that, against company rules :(

**Comment by xperiandri** [comment]
Then fix yourself and post to StackOwerflow 😄

**Comment by rizi** [comment]
@ghost where did you get the id: <Framework Id=262407
