### ISSUE TITLE
Crashes when migrating

### ISSUE THREAD

**Issue by sallgeud** [TargetFrameworkMigrator/TargetFrameworkMigrator#42]
When migrating, the migrator becomes unresponsive and then hard crashes all of visual studio.

**Comment by mellamokb** [comment]
I'm having this problem as well.  Seems to be inconsistent.  I upgraded 5 separate solutions (with some overlapping referenced projects).  They are all medium size, having 10-20 projects each.  3 of them worked fine, 2 of them hard crashed Visual Studio 2017.

When I bring Visual Studio back up on the solutions that crashed, some of them aren't upgraded.  So it does seem to be related to specific projects causing the crash.

**Comment by 304NotModified** [comment]
Should be fixed in 1.7. If not please create a new issue
