### ISSUE TITLE
Error opening a solution

### ISSUE THREAD

**Issue by matteomigliore** [TargetFrameworkMigrator/TargetFrameworkMigrator#46]
Hi!

When I open a solution, I obtain this error:
![image](https://user-images.githubusercontent.com/432974/37621720-1ad7c7ca-2bc0-11e8-9374-a3b1ba59ef70.png)

If you do not, I suggest you to use Exceptionless to get errors from the installed plugins.

Thank you.

**Comment by 304NotModified** [comment]
This should be fixed in 1.7. If not, please open a new issue.
