### ISSUE TITLE
Support .Net 4.7.2

### ISSUE THREAD

**Issue by jeffchen-codingconsultantco** [TargetFrameworkMigrator/TargetFrameworkMigrator#49]

**Comment by stevenevans-j2** [comment]
Is the fix the same as for 4.7.1m if so what is the FrameworkId?

**Comment by rizi** [comment]
@stevenevans-j2 yes it's the same fix, see my comment above or here

**Comment by rbmanian75** [comment]
Will there be a fix for this or any work around is there?

**Comment by paulbradbury** [comment]
The workaround is to add the entry above into the frameworks XML file that sits with the binaries installed in your local app settings Visual studio folder. Once that's in, you'll see it picked as an option to migrate to. 4.7.2 much, much better with netstandard2.0 so this is a very useful trick...

**Comment by thomaswurtz** [comment]
Great tip! @paulbradbury 
Was a bit difficult to find the exact location of the Framework.xml to edit though.
For me this was located in this folder:
C:\Users\username\AppData\Local\Microsoft\VisualStudio\15.0_db7b49e2\Extensions\weipm2gu.wsw

Updated Framework.xml to this and it worked like a charm! 😃 
```
<?xml version="1.0" encoding="utf-8" ?>
<Frameworks>
  <Framework Id="262663" Name=".NETFramework,Version=v4.7.2"/>
  <Framework Id="262407" Name=".NETFramework,Version=v4.7.1"/>
  <Framework Id="262151" Name=".NETFramework,Version=v4.7"/>
  <Framework Id="262662" Name=".NETFramework,Version=v4.6.2"/>
  <Framework Id="262406" Name=".NETFramework,Version=v4.6.1"/>
  <Framework Id="262150" Name=".NETFramework,Version=v4.6"/>
  <Framework Id="262661" Name=".NETFramework,Version=v4.5.2"/>
  <Framework Id="262405" Name=".NETFramework,Version=v4.5.1"/>
  <Framework Id="262149" Name=".NETFramework,Version=v4.5"/>
  <Framework Id="262144" Name=".NETFramework,Version=v4.0"/>
  <Framework Id="262144" Name=".NETFramework,Version=v4.0,Profile=Client"/>
  <Framework Id="196613" Name=".NETFramework,Version=v3.5"/>
  <Framework Id="196613" Name=".NETFramework,Version=v3.5,Profile=Client"/>
  <Framework Id="196608" Name=".NETFramework,Version=v3.0"/>
  <Framework Id="131072" Name=".NETFramework,Version=v2.0"/>
</Frameworks>
```
