### ISSUE TITLE
Project owner should pass the baton

### ISSUE THREAD

**Issue by michael-jennings** [TargetFrameworkMigrator/TargetFrameworkMigrator#51]
Looks like this project is still in demand and PRs are waiting to make it in & keep it up to date, but it seems abandoned.  Would the project owner please nominate 2-3 people, give them full admin access to this project, and let your wonderful code baby live happily ever after in the hands of whoever cares to review/merge PRs for it?  Perhaps just pick the most recent decent looking PRs and give it to those who submitted them.  Stipulate that they are also bound to pass on the baton to someone else if either they grow tired of managing it, or notice that a fellow owner has disappeared and needs replacing.

**Comment by JimHume** [comment]
I agree that the baton should be passed.
To facilitate this, someone may want to create a pull request that adds a LICENSE.md file to the repository, and removes any 'copyright' text within the files in the repository.
From https://help.github.com/articles/licensing-a-repository/
```
without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.
```

I can foresee this project being useful for more complex scenarios (multiple target frameworks, for example) and it would be a shame to start from scratch on a new project when this one is already solid.

**Comment by 304NotModified** [comment]
Polite Bump @vansickle

**Comment by vansickle** [comment]
@304NotModified ready to take care about the project?

**Comment by vansickle** [comment]
If anyone ready to maintain the project - tell me, I'll give them rights

**Comment by 304NotModified** [comment]
I like to have rights and I really like to have other maintainers as well (so please let us know!)

I really like this extension and it would be great to release a new version of it. So if I like to start with merging PRs (and close duplicate PRs) and release a new version.

**Comment by 304NotModified** [comment]
and setup a CI :)

**Comment by vansickle** [comment]
@304NotModified Migrated to separate organization and invited you to be the owner of it. I totally second setting up an CI if it's possible for VS extension. 
If you do all that work I would be happy to publish new builds to VS marketplace.

**Comment by 304NotModified** [comment]
Cool, will do the CI this week

**Comment by 304NotModified** [comment]
Close this for now :)

(If there are others who like to maintain, please let us know! I will create a new issue for that later this week)
