### ISSUE TITLE
Database project migration crashes with unknown COM Exception

### ISSUE THREAD

**Issue by xperiandri** [TargetFrameworkMigrator/TargetFrameworkMigrator#54]
When I try to migrate `sqlproj` migrator crashes [here](https://github.com/VHQLabs/TargetFrameworkMigrator/blob/6f999b8f397fe225bfcab77d5ae15a8ab16ccc6e/TargetFrameworkMigrator/Migrator.cs#L203) unabling to cast property to some interface

**Comment by 304NotModified** [comment]
Thanks for the bug support!

**Comment by 304NotModified** [comment]
With 1.7 I can't reproduce this. (the sqlproj is not in the list then).
