### ISSUE TITLE
Support .NET 4.8

### ISSUE THREAD

**Issue by mastermattie** [TargetFrameworkMigrator/TargetFrameworkMigrator#56]
In order to add .NET 4.8, the Id 262152 should be added.
It looks like the ID can be generated by taking the version number, swap the last two parts, and convert from hex to dec, for example:
 
**Version: 2.0**
> **Hex** 02 00 00
> **Dec** 131072
 
**Version: 3.5**
> **Hex** 03 00 05
> **Dec** 196613
 
**Version: 4.0**
> **Hex** 04 00 00
> **Dec** 262144

**Version: 4.5**
> **Hex** 04 00 05
> **Dec** 262149
 
**Version: 4.5.1**
> **Hex** 04 01 05
> **Dec** 262405
 
**Version: 4.5.2**
> **Hex** 04 02 05
> **Dec** 262661
 
**Version: 4.6**
> **Hex** 04 00 06
> **Dec** 262150
 
**Version: 4.6.1**
> **Hex** 04 01 06
> **Dec** 262406
 
**Version: 4.6.2**
> **Hex** 04 02 06
> **Dec** 262662
 
**Version 4.7**
> **Hex** 04 00 07
> **Dec** 262151
 
**Version 4.7.1**
> **Hex** 04 01 07
> **Dec** 262407
 
**Version 4.7.2**
> **Hex** 04 02 07
> **Dec** 262663
 
**Version 4.8**
> **Hex** 04 00 08
> **Dec** 262152

**Comment by Ian1971** [comment]
I created #57 but that was before I spotted this issue.  I had no idea about those ids. What is the significance of them, as it seems to work anyway?
