### ISSUE TITLE
Needs help in building / running automated tests

### ISSUE THREAD

**Issue by 304NotModified** [TargetFrameworkMigrator/TargetFrameworkMigrator#64]
Hi,

I'm trying to get everything building (and green tests) for a new version.

Unfortunately if have several issues with the build and the tests. Local and on CI have troubles. (tried on the CI VS2013,2015,2017,2019)

Is there someone who has the project building? Which Visual Studio do you use? Are the tests green? 

Thanks for the response in advance!

**Comment by 304NotModified** [comment]
@Edward84 @xperiandri @Edward84 I saw some awesome stuff of you (the PRs). Could you help me with this quest?

**Comment by 304NotModified** [comment]
@vansickle I you have some insights, please share :)

**Comment by 304NotModified** [comment]
If I add a copy of Microsoft.VisualStudio.Shell.Framework.dll (v15) to git, then I get it building locally under VS 2019. The tests give me these issues:

- unit tests, DTE is `null` and then Microsoft.VisualStudio.Shell.Framework.dll
- integration tests:  cannot start tests, 

    ```
    The test adapter ('Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') 
    required to execute this test could not be loaded. Check that the test adapter is installed properly. 
    Object reference not set to an instance of an object.
    Stacktrace is not available
    ```

**Comment by xperiandri** [comment]
But it must be available as NuGet

**Comment by xperiandri** [comment]
I guess 2017 have to work, but 2019 is prefferable

**Comment by 304NotModified** [comment]
> But it must be available as NuGet

Do you mean Microsoft.VisualStudio.Shell.Framework.dll ? Yes it is, but it's from an unknown source



> I guess 2017 have to work, but 2019 is preferable

What's working for you (locally?)

**Comment by xperiandri** [comment]
https://github.com/xperiandri/TargetFrameworkMigrator/blob/31f53001ca45c99e14ea2689cc9d2c64bd522a60/TargetFrameworkMigrator.sln#L4

Last time I opened it with Visual Studio 2017

**Comment by 304NotModified** [comment]
any green tests at your side?

**Comment by xperiandri** [comment]
![image](https://user-images.githubusercontent.com/2365592/71130434-8bd8c000-21fa-11ea-97a8-bdc562bad6f6.png)

This references currently come from NuGet

![image](https://user-images.githubusercontent.com/2365592/71130533-c6425d00-21fa-11ea-898f-d01882d54aae.png)

**Comment by xperiandri** [comment]
I guess you must update Unit Test projects to target the framwork version of Microsoft.VSSDK.UnitTestLibrary

![image](https://user-images.githubusercontent.com/2365592/71132899-829f2180-2201-11ea-853b-93a4f6306360.png)

**Comment by xperiandri** [comment]
Try to continue with https://github.com/xperiandri/TargetFrameworkMigrator/tree/project-upgrade

**Comment by 304NotModified** [comment]
> Try to continue with https://github.com/xperiandri/TargetFrameworkMigrator/tree/project-upgrade

Thanks! But i'm not sure if we should https://github.com/TargetFrameworkMigrator/TargetFrameworkMigrator/pull/41 yet. So for now I just added the .dll to the repo.

**Comment by Ian1971** [comment]
I am able to get it to build in vs2019 with a hint path to Microsoft.VisualStudio.Shell.11.0.dll and copying Source.extension.vsixmanifest to TargetFrameworkMigrator though obviously having it in two places isn't ideal. I'm pretty much a vsix newbie so I don't really know why it wants the manifest file there as well as in the TargetFrameworkMigratorVSIX project

**Comment by Ian1971** [comment]
Test failed though. Trying to fix all the refs and see where that ends up.

**Comment by Ian1971** [comment]
So I can get it to build and unit tests pass. But I seem to be bashing my head against a wall with the integration tests because they deprecated HostType attribute.

**Comment by Ian1971** [comment]
I created pr #78 if you want to carry on with it. It builds the vsix, and it seems to install but I can't find the UI once installed.

**Comment by 304NotModified** [comment]
Thanks! I will have a look.

The status for now:

- it works on VS2019 on my machine. (build, unit tests green, integration tests red)
- it works on VS2017 on Appveyor. (build, unit tests green, integration tests red). But build fails on VS2019 there. Really strange. 
- it fails on Azure devops (build). Tried VS2012/VS2013/VS2015/VS2017/VS2019. So I will stick to AppVeyor.

**Comment by xperiandri** [comment]
Check that you use latest server on Azure DevOps. That changed pools.
Also I guess you need to install or request Visual Studio Shell to be present

**Comment by 304NotModified** [comment]
Its azure devops in the cloud :)

**Comment by xperiandri** [comment]
Yes, similarly to requesting .NET Core beta versions there you can request Visual Studio SDK stuff

**Comment by 304NotModified** [comment]
It works anyway on the CI, so I think we can close this for now. Thanks for the help!
