### ISSUE TITLE
Crash on VS2019 (master)

### ISSUE THREAD

**Issue by 304NotModified** [TargetFrameworkMigrator/TargetFrameworkMigrator#83]
crash after clicking migrate

![image](https://user-images.githubusercontent.com/5808377/73501045-bd7da300-43c4-11ea-9b94-e5fd22c63c7e.png)

**Comment by 304NotModified** [comment]
But not if run from debugger :(

**Comment by 304NotModified** [comment]
related? #42

**Comment by xperiandri** [comment]
Ah, I run from debugger

**Comment by 304NotModified** [comment]
yes, me too. And just before release I did a final test, and failed :'(

**Comment by 304NotModified** [comment]
@xperiandri could you reproduce the issue?

**Comment by kkapuscinski** [comment]
I have stumbled upon the same problem. I found in Stytem EventLog that System.NullReferenceException occurs in  System.Windows.Forms.

It looks that it happens after migrating all csproj files.

Ill try to find more details.

**Comment by 304NotModified** [comment]
Please do. In stuck in this. There isn't a crash when debugging the extension :/

**Comment by kkapuscinski** [comment]
Yeah, but in Debug window i get Exception thrown: 'System.InvalidOperationException' in System.Windows.Forms.dll.

I am almost certain that there is problem with Thread synchronization context, but i dont have evidence yet :)

**Comment by kkapuscinski** [comment]
ok i narrowed problem to this line
`projectsUpdateList.Projects = LoadProjects();`

probably thats the problem
https://stackoverflow.com/questions/8621350/why-do-i-get-this-nullreferenceexception-c-sharp

but such code
`this.Invoke(delegate(DataTable table)
 {
     dgvComputers1.DataSource = table;
 }, dt);`

is already used 

`set
      {
        var wrapperBindingList = new SortableBindingList<ProjectModel>(value);
        try
        {
          dataGridView1.DataSource = wrapperBindingList;
          dataGridView1.Refresh();
        }
        catch (InvalidOperationException)
        {
          Invoke(new EventHandler(delegate
          {
            dataGridView1.DataSource = wrapperBindingList;
            dataGridView1.Refresh();
          }));
       `

maybe setting DataSource completes without problem and exception is throwed on Refresh().

**Comment by 304NotModified** [comment]
@kkapuscinski any idea how to fix this?

**Comment by kkapuscinski** [comment]
@304NotModified not yet. Tried several things but i am no expert in Win Forms so probably i lack of some knowledge. But ill try harder :)

**Comment by kkapuscinski** [comment]
@304NotModified  ok i probably found a solution. code for now is in gist but later ill make PR
https://gist.github.com/kkapuscinski/83321a0cfce33eb391cef0677adefe0c

made few runs without problem. It was happeening because of System.InvalidOperationException and then switching thread (maybe some invalid state of control) but i dont have any specific reason or link to similar problem

**Comment by 304NotModified** [comment]
Pr would be great! Will test it also then. :)

**Comment by kkapuscinski** [comment]
#85 here it is

**Comment by 304NotModified** [comment]
Cannot reproduce the issue :)
