### ISSUE TITLE
Cannot install/upgrade in Visual Studio 2017 because Microsoft.VisualStudio.Component.VSSDK is missing

### ISSUE THREAD

**Issue by icnocop** [TargetFrameworkMigrator/TargetFrameworkMigrator#88]
Hi.

Thank you for the continued development.

Similar to https://github.com/TargetFrameworkMigrator/TargetFrameworkMigrator/issues/58 and https://github.com/TargetFrameworkMigrator/TargetFrameworkMigrator/issues/84, when trying to upgrade this extension from 1.6.5 to 1.7.0 in Visual Studio 2017, I get the following error:
```
Target Framework Migrator
This extension cannot be installed because the following references are missing: Microsoft.VisualStudio.Component.VSSDK
```
![image](https://user-images.githubusercontent.com/507649/99890865-6d542380-2c18-11eb-8670-91938ec1d13b.png)

I was able to install v1.7.0 of this extension in Visual Studio 2019 without issues.

**Comment by Freddyvdh** [comment]
Same problem here, I only have VS 2017 but the same problem.

**Comment by dhananjaykurekar25** [comment]
I am also getting the same issue while installing on VS 2017.

**Comment by jmorgan-habs** [comment]
Same here. Any plans for a fix?

**Comment by 304NotModified** [comment]
This has something to do with, see #58

https://github.com/TargetFrameworkMigrator/TargetFrameworkMigrator/blob/ad5ffb38b460e57cf83c76d9bfa02ad1e3ca095f/Src/TargetFrameworkMigrator/source.extension.vsixmanifest#L20
