### ISSUE TITLE
Nuget packages.config old framework version

### ISSUE THREAD

**Issue by vansickle** [TargetFrameworkMigrator/TargetFrameworkMigrator#9]
From visualstudio gallery review:

by Bernardo Loureiro | Thu 5:57 PM

I had some troubles with nuget packages, when in packages.config files, the targetFramework stay in old framework version.
Maybe, would a good ideia change this attribute in packages.config too.

**Comment by xperiandri** [comment]
Use `Update-Package -reinstall`
I think this need to be done as a part of migration process.

**Comment by 304NotModified** [comment]
There a no plans for this, so closing this issue
