### ISSUE TITLE
This extension is not installable on any currently installed products(VS 2019 Community)

### ISSUE THREAD

**Issue by andre-artus** [TargetFrameworkMigrator/TargetFrameworkMigrator#95]
I tried to install this from within VS 2019 and also tried direct download from the marketplace, but I keep running into an error, shown here (I elided file paths):

2021/08/09 17:24:41 - Microsoft VSIX Installer
2021/08/09 17:24:41 - -------------------------------------------
2021/08/09 17:24:41 - vsixinstaller.exe version:
2021/08/09 17:24:41 - 17.0.2145-preview2
2021/08/09 17:24:41 - -------------------------------------------
2021/08/09 17:24:41 - Command line parameters:
2021/08/09 17:24:41 - [...]\VSIXInstaller.exe,[...]\TargetFrameworkMigrator.vsix
2021/08/09 17:24:41 - -------------------------------------------
2021/08/09 17:24:41 - Microsoft VSIX Installer
2021/08/09 17:24:41 - -------------------------------------------
2021/08/09 17:24:41 - Initializing Install...
2021/08/09 17:24:41 - Extension Details...
2021/08/09 17:24:41 - 	Identifier         : TargetFrameworkMigrator..4f7666b9-e62c-46a1-af25-21ab8742ef00
2021/08/09 17:24:41 - 	Name               : Target Framework Migrator
2021/08/09 17:24:41 - 	Author             : VHQLabs
2021/08/09 17:24:41 - 	Version            : 1.7.0
2021/08/09 17:24:41 - 	Description        : Change all your .Net projects Target Framework at once
2021/08/09 17:24:41 - 	Locale             : en-US
2021/08/09 17:24:41 - 	MoreInfoURL        : 
2021/08/09 17:24:41 - 	InstalledByMSI     : False
2021/08/09 17:24:41 - 	SupportedFrameworkVersionRange : [4.5,)
2021/08/09 17:24:41 - 
2021/08/09 17:24:41 - 	SignatureState     : Unsigned
2021/08/09 17:24:41 - 	Supported Products : 
2021/08/09 17:24:41 - 		Microsoft.VisualStudio.Pro
2021/08/09 17:24:41 - 			Version : [11.0,17.0]
2021/08/09 17:24:41 - 			ProductArchitecture : notSpecified
2021/08/09 17:24:41 - 		Microsoft.VisualStudio.Community
2021/08/09 17:24:41 - 			Version : [11.0,17.0]
2021/08/09 17:24:41 - 			ProductArchitecture : notSpecified
2021/08/09 17:24:41 - 		Microsoft.VisualStudio.Enterprise
2021/08/09 17:24:41 - 			Version : [11.0,17.0]
2021/08/09 17:24:41 - 			ProductArchitecture : notSpecified
2021/08/09 17:24:41 - 
2021/08/09 17:24:41 - 	References         : 
2021/08/09 17:24:41 - 	Prerequisites      : 
2021/08/09 17:24:41 - 		-------------------------------------------------------
2021/08/09 17:24:41 - 		Identifier   : Microsoft.VisualStudio.Component.VSSDK
2021/08/09 17:24:41 - 		Name         : Visual Studio SDK
2021/08/09 17:24:41 - 		Version      : [16.0.28315.86,17.0)
2021/08/09 17:24:41 - 
2021/08/09 17:24:41 - Signature Details...
2021/08/09 17:24:41 - 	Extension is not signed.
2021/08/09 17:24:41 - 
2021/08/09 17:24:41 - Searching for applicable products...
2021/08/09 17:24:41 - Found installed product - Global Location
2021/08/09 17:24:41 - Found installed product - Visual Studio Community 2019
2021/08/09 17:24:41 - Found installed product - Visual Studio Community 2022 Preview
2021/08/09 17:24:41 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

The download page does not list any restrictions, in fact it claims "Supports VS2012-VS2019, all editions". If support for VS 2019 Community is intended then what could be the cause of the issue?

**Comment by andre-artus** [comment]
When I clone the project and run the VSIX project it installs and runs in a test instance of VS 2019 just fine. When I build the VSIX project and try to install it, then it does not work, just as above.

**Comment by 304NotModified** [comment]
I have locally the same issue, and also running it local with the test instance. Thus I cannot install nor test it. Not sure what happened! 

Funny as I installed the version when it was released without issues

**Comment by 304NotModified** [comment]
Please confirm this one is working :)

https://ci.appveyor.com/api/buildjobs/5v2fp6w96ph877ek/artifacts/Src%2FTargetFrameworkMigratorVSIX%2Fbin%2FRelease%2FTargetFrameworkMigrator.vsix

**Comment by 304NotModified** [comment]
tested it, this is fixed with 1.7.1

currently not on VS marketplace yet (I don't have the rights). You could download it from here: https://ci.appveyor.com/project/304NotModified/targetframeworkmigrator/builds/40344853/artifacts
